//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaiGame7.Model.EFModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HaiGame7Entities : DbContext
    {
        public HaiGame7Entities()
            : base("name=HaiGame7Entities")
        {
            Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<db_Article> db_Article { get; set; }
        public virtual DbSet<db_ArticleComment> db_ArticleComment { get; set; }
        public virtual DbSet<db_AssetRecord> db_AssetRecord { get; set; }
        public virtual DbSet<db_CommonUseHero> db_CommonUseHero { get; set; }
        public virtual DbSet<db_DateFight> db_DateFight { get; set; }
        public virtual DbSet<db_FightResult> db_FightResult { get; set; }
        public virtual DbSet<db_FightState> db_FightState { get; set; }
        public virtual DbSet<db_Follow> db_Follow { get; set; }
        public virtual DbSet<db_Game> db_Game { get; set; }
        public virtual DbSet<db_GameIDofUser> db_GameIDofUser { get; set; }
        public virtual DbSet<db_GameInfoofPlatform> db_GameInfoofPlatform { get; set; }
        public virtual DbSet<db_GameRecord> db_GameRecord { get; set; }
        public virtual DbSet<db_GuessAndVote> db_GuessAndVote { get; set; }
        public virtual DbSet<db_GuessFight> db_GuessFight { get; set; }
        public virtual DbSet<db_GuessFightLink> db_GuessFightLink { get; set; }
        public virtual DbSet<db_GuessOption> db_GuessOption { get; set; }
        public virtual DbSet<db_GuessRecord> db_GuessRecord { get; set; }
        public virtual DbSet<db_Message> db_Message { get; set; }
        public virtual DbSet<db_MyCollection> db_MyCollection { get; set; }
        public virtual DbSet<db_QRCode> db_QRCode { get; set; }
        public virtual DbSet<db_Report> db_Report { get; set; }
        public virtual DbSet<db_SysMessage> db_SysMessage { get; set; }
        public virtual DbSet<db_Team> db_Team { get; set; }
        public virtual DbSet<db_TeamBlog> db_TeamBlog { get; set; }
        public virtual DbSet<db_TeamUser> db_TeamUser { get; set; }
        public virtual DbSet<db_UnAnswer> db_UnAnswer { get; set; }
        public virtual DbSet<db_User> db_User { get; set; }
    }
}
